### ISSUE TITLE
Failed to load a language-blade package grammar

### ISSUE THREAD

**Issue by nbdamian** [jawee/language-blade#39]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.1
**System**: Ubuntu 14.04.4
**Thrown From**: [language-blade](https://github.com/jawee/language-blade) package, v0.24.1

### Stack Trace

Failed to load a language-blade package grammar

```
At Grammar missing required scopeName property: /home/damian/.atom/packages/language-blade/grammars/blade.cson in /home/damian/.atom/packages/language-blade/grammars/blade.cson

Error: Grammar missing required scopeName property: /home/damian/.atom/packages/language-blade/grammars/blade.cson
    at /usr/share/atom/resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:122:64
    at /usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:180:53
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
  at /home/damian/.atom/packages/language-blade/grammars/blade.cson:1:1
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-beautify",
      "sublime-block-comment"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.20
color-picker, v2.1.1
css-specificity, v0.2.2
emmet, v2.4.3
jquery-snippets, v11.0.0
language-blade, v0.24.1
linter, v1.11.4
linter-bootlint, v1.0.2
linter-csslint, v1.3.2
linter-htmlhint, v1.1.1
linter-jshint, v2.0.3
linter-php, v1.2.0
local-history, v3.2.3
minimap, v4.21.0
project-manager, v2.9.0
project-viewer, v0.2.31
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Ingramz** [comment]
Hi and thank you for the report.

Could you please check if the contents of `/home/damian/.atom/packages/language-blade/grammars/blade.cson` is the same as https://github.com/jawee/language-blade/blob/master/grammars/blade.cson

**Comment by nbdamian** [comment]
No, for some reason blade.cson is empty.

**Comment by Ingramz** [comment]
In that case try reinstalling the package. If that doesn't help, we should be looking into reporting a bug at atom/atom.

**Comment by Ingramz** [comment]
Closing this for now.
