### ISSUE TITLE
Unable to update on Fedora 25

### ISSUE THREAD

**Issue by rained23** [jawee/language-blade#64]
```
/bin/sh: /bin/electron: No such file or directory


gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@6.9.2 | linux | x64
gyp ERR! install error 
gyp ERR! stack Error: Invalid version number: undefined
gyp ERR! stack     at install (/usr/lib/node_modules/node-gyp/lib/install.js:50:21)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/lib/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/usr/lib/node_modules/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/node-gyp/bin/node-gyp.js:133:1)
gyp ERR! stack     at Module._compile (module.js:570:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:579:10)
gyp ERR! stack     at Module.load (module.js:487:32)
gyp ERR! stack     at tryModuleLoad (module.js:446:12)
gyp ERR! stack     at Function.Module._load (module.js:438:3)
gyp ERR! stack     at Module.runMain (module.js:604:10)
gyp ERR! System Linux 4.8.15-300.fc25.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=undefined" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /home/cruzer/.atom
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
```

**Comment by Ingramz** [comment]
@rained23 Unfortunately this has nothing to do with the implementation of this package. The issues you are experiencing are from Atom or its combination with Fedora.

Quick google search found me this issue, unsure if it is related to what you are using, but perhaps it can help you: https://github.com/FZUG/repo/issues/152

Feel free to close this issue at any point of time if you don't have any further questions.

**Comment by rained23** [comment]
I will try to report this bug on the atom package maintainer for the copr.
