### ISSUE TITLE
Failed to activate the language-blade package

### ISSUE THREAD

**Issue by ThibaultModat** [jawee/language-blade#88]
The last update of the package create this bug

**Atom**: 1.31.0 x64
**Electron**: 2.0.7
**OS**: Debian GNU/Linux
**Thrown From**: [language-blade](https://github.com/jawee/language-blade) package 0.41.2

### Stack Trace

Failed to activate the language-blade package

```
At Unexpected token export

SyntaxError: Unexpected token export
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:782:33)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:220:40)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:696:42)
    at config.transactAsync (/usr/share/atom/resources/app/src/package-manager.js:671:36)
    at Config.transactAsync (/usr/share/atom/resources/app/src/config.js:852:28)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:669:23)
    at PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:648:50)
    at loadStatePromise.loadState.then (/usr/share/atom/resources/app/src/atom-environment.js:875:27)
    at <anonymous>
```

### Non-Core Packages

```
absent-contrast-rainglow-syntax 1.0.0 
absent-light-rainglow-syntax 1.0.0 
absent-rainglow-syntax 1.0.0 
allure-contrast-rainglow-syntax 1.0.0 
allure-light-rainglow-syntax 1.0.0 
allure-rainglow-syntax 1.0.0 
arstotzka-contrast-rainglow-syntax 1.0.0 
arstotzka-light-rainglow-syntax 1.0.0 
arstotzka-rainglow-syntax 1.0.0 
atom-autocomplete-php 0.25.6 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
azure-contrast-rainglow-syntax 1.0.0 
azure-light-rainglow-syntax 1.0.0 
azure-rainglow-syntax 1.0.0 
banner-contrast-rainglow-syntax 1.0.0 
banner-light-rainglow-syntax 1.0.0 
banner-rainglow-syntax 1.0.0 
blink-contrast-rainglow-syntax 1.0.0 
blink-light-rainglow-syntax 1.0.0 
blink-rainglow-syntax 1.0.0 
bold-contrast-rainglow-syntax 1.0.0 
bold-light-rainglow-syntax 1.0.0 
bold-rainglow-syntax 1.0.0 
boxuk-contrast-rainglow-syntax 1.0.0 
boxuk-light-rainglow-syntax 1.0.0 
boxuk-rainglow-syntax 1.0.0 
brave-contrast-rainglow-syntax 1.0.0 
brave-light-rainglow-syntax 1.0.0 
brave-rainglow-syntax 1.0.0 
carbonight-contrast-rainglow-syntax 1.0.0 
carbonight-light-rainglow-syntax 1.0.0 
carbonight-rainglow-syntax 1.0.0 
chocolate-contrast-rainglow-syntax 1.0.0 
chocolate-light-rainglow-syntax 1.0.0 
chocolate-rainglow-syntax 1.0.0 
codecourse-contrast-rainglow-syntax 1.0.0 
codecourse-light-rainglow-syntax 1.0.0 
codecourse-rainglow-syntax 1.0.0 
coffee-contrast-rainglow-syntax 1.0.0 
coffee-light-rainglow-syntax 1.0.0 
coffee-rainglow-syntax 1.0.0 
comrade-contrast-rainglow-syntax 1.0.0 
comrade-light-rainglow-syntax 1.0.0 
comrade-rainglow-syntax 1.0.0 
crackpot-contrast-rainglow-syntax 1.0.0 
crackpot-light-rainglow-syntax 1.0.0 
crackpot-rainglow-syntax 1.0.0 
crisp-contrast-rainglow-syntax 1.0.0 
crisp-light-rainglow-syntax 1.0.0 
crisp-rainglow-syntax 1.0.0 
dare-contrast-rainglow-syntax 1.0.0 
dare-light-rainglow-syntax 1.0.0 
dare-rainglow-syntax 1.0.0 
darkside-contrast-rainglow-syntax 1.0.0 
darkside-light-rainglow-syntax 1.0.0 
darkside-rainglow-syntax 1.0.0 
downpour-contrast-rainglow-syntax 1.0.0 
downpour-light-rainglow-syntax 1.0.0 
downpour-rainglow-syntax 1.0.0 
earthsong-contrast-rainglow-syntax 1.0.0 
earthsong-light-rainglow-syntax 1.0.0 
earthsong-rainglow-syntax 1.0.0 
emmet 2.4.3 
fodder-contrast-rainglow-syntax 1.0.0 
fodder-light-rainglow-syntax 1.0.0 
fodder-rainglow-syntax 1.0.0 
fonts 3.1.0 
frantic-contrast-rainglow-syntax 1.0.0 
frantic-light-rainglow-syntax 1.0.0 
frantic-rainglow-syntax 1.0.0 
freshcut-contrast-rainglow-syntax 1.0.0 
freshcut-light-rainglow-syntax 1.0.0 
freshcut-rainglow-syntax 1.0.0 
friction-contrast-rainglow-syntax 1.0.0 
friction-light-rainglow-syntax 1.0.0 
friction-rainglow-syntax 1.0.0 
frontier-contrast-rainglow-syntax 1.0.0 
frontier-light-rainglow-syntax 1.0.0 
frontier-rainglow-syntax 1.0.0 
github-contrast-rainglow-syntax 1.0.0 
github-light-rainglow-syntax 1.0.0 
github-rainglow-syntax 1.0.0 
glance-contrast-rainglow-syntax 1.0.0 
glance-light-rainglow-syntax 1.0.0 
glance-rainglow-syntax 1.0.0 
gloom-contrast-rainglow-syntax 1.0.0 
gloom-light-rainglow-syntax 1.0.0 
gloom-rainglow-syntax 1.0.0 
glowfish-contrast-rainglow-syntax 1.0.0 
glowfish-light-rainglow-syntax 1.0.0 
glowfish-rainglow-syntax 1.0.0 
goldfish-contrast-rainglow-syntax 1.0.0 
goldfish-light-rainglow-syntax 1.0.0 
goldfish-rainglow-syntax 1.0.0 
goto-definition 1.3.4 
grunge-contrast-rainglow-syntax 1.0.0 
grunge-light-rainglow-syntax 1.0.0 
grunge-rainglow-syntax 1.0.0 
halflife-contrast-rainglow-syntax 1.0.0 
halflife-light-rainglow-syntax 1.0.0 
halflife-rainglow-syntax 1.0.0 
hawaii-contrast-rainglow-syntax 1.0.0 
hawaii-light-rainglow-syntax 1.0.0 
hawaii-rainglow-syntax 1.0.0 
heroku-contrast-rainglow-syntax 1.0.0 
heroku-light-rainglow-syntax 1.0.0 
heroku-rainglow-syntax 1.0.0 
hive-contrast-rainglow-syntax 1.0.0 
hive-light-rainglow-syntax 1.0.0 
hive-rainglow-syntax 1.0.0 
horizon-contrast-rainglow-syntax 1.0.0 
horizon-light-rainglow-syntax 1.0.0 
horizon-rainglow-syntax 1.0.0 
hub-contrast-rainglow-syntax 1.0.0 
hub-light-rainglow-syntax 1.0.0 
hub-rainglow-syntax 1.0.0 
hyrule-contrast-rainglow-syntax 1.0.0 
hyrule-light-rainglow-syntax 1.0.0 
hyrule-rainglow-syntax 1.0.0 
iceberg-contrast-rainglow-syntax 1.0.0 
iceberg-light-rainglow-syntax 1.0.0 
iceberg-rainglow-syntax 1.0.0 
isotope-contrast-rainglow-syntax 1.0.0 
isotope-light-rainglow-syntax 1.0.0 
isotope-rainglow-syntax 1.0.0 
jewel-contrast-rainglow-syntax 1.0.0 
jewel-light-rainglow-syntax 1.0.0 
jewel-rainglow-syntax 1.0.0 
jingle-contrast-rainglow-syntax 1.0.0 
jingle-light-rainglow-syntax 1.0.0 
jingle-rainglow-syntax 1.0.0 
joker-contrast-rainglow-syntax 1.0.0 
joker-light-rainglow-syntax 1.0.0 
joker-rainglow-syntax 1.0.0 
juicy-contrast-rainglow-syntax 1.0.0 
juicy-light-rainglow-syntax 1.0.0 
juicy-rainglow-syntax 1.0.0 
jumper-contrast-rainglow-syntax 1.0.0 
jumper-light-rainglow-syntax 1.0.0 
jumper-rainglow-syntax 1.0.0 
keen-contrast-rainglow-syntax 1.0.0 
keen-light-rainglow-syntax 1.0.0 
keen-rainglow-syntax 1.0.0 
kiwi-contrast-rainglow-syntax 1.0.0 
kiwi-light-rainglow-syntax 1.0.0 
kiwi-rainglow-syntax 1.0.0 
language-blade 0.41.2 
language-latex 1.2.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
laracasts-contrast-rainglow-syntax 1.0.0 
laracasts-light-rainglow-syntax 1.0.0 
laracasts-rainglow-syntax 1.0.0 
laravel-contrast-rainglow-syntax 1.0.0 
laravel-light-rainglow-syntax 1.0.0 
laravel-rainglow-syntax 1.0.0 
lavender-contrast-rainglow-syntax 1.0.0 
lavender-light-rainglow-syntax 1.0.0 
lavender-rainglow-syntax 1.0.0 
legacy-contrast-rainglow-syntax 1.0.0 
legacy-light-rainglow-syntax 1.0.0 
legacy-rainglow-syntax 1.0.0 
lichen-contrast-rainglow-syntax 1.0.0 
lichen-light-rainglow-syntax 1.0.0 
lichen-rainglow-syntax 1.0.0 
loyal-contrast-rainglow-syntax 1.0.0 
loyal-light-rainglow-syntax 1.0.0 
loyal-rainglow-syntax 1.0.0 
mauve-contrast-rainglow-syntax 1.0.0 
mauve-light-rainglow-syntax 1.0.0 
mauve-rainglow-syntax 1.0.0 
mellow-contrast-rainglow-syntax 1.0.0 
mellow-light-rainglow-syntax 1.0.0 
mellow-rainglow-syntax 1.0.0 
mintchoc-contrast-rainglow-syntax 1.0.0 
mintchoc-light-rainglow-syntax 1.0.0 
mintchoc-rainglow-syntax 1.0.0 
morass-contrast-rainglow-syntax 1.0.0 
morass-light-rainglow-syntax 1.0.0 
morass-rainglow-syntax 1.0.0 
mud-contrast-rainglow-syntax 1.0.0 
mud-light-rainglow-syntax 1.0.0 
mud-rainglow-syntax 1.0.0 
newton-contrast-rainglow-syntax 1.0.0 
newton-light-rainglow-syntax 1.0.0 
newton-rainglow-syntax 1.0.0 
otakon-contrast-rainglow-syntax 1.0.0 
otakon-light-rainglow-syntax 1.0.0 
otakon-rainglow-syntax 1.0.0 
overflow-contrast-rainglow-syntax 1.0.0 
overflow-light-rainglow-syntax 1.0.0 
overflow-rainglow-syntax 1.0.0 
pastel-contrast-rainglow-syntax 1.0.0 
pastel-light-rainglow-syntax 1.0.0 
pastel-rainglow-syntax 1.0.0 
patriot-contrast-rainglow-syntax 1.0.0 
patriot-light-rainglow-syntax 1.0.0 
patriot-rainglow-syntax 1.0.0 
peacock-contrast-rainglow-syntax 1.0.0 
peacock-light-rainglow-syntax 1.0.0 
peacock-rainglow-syntax 1.0.0 
peacocks-in-space-contrast-rainglow-syntax 1.0.0 
peacocks-in-space-light-rainglow-syntax 1.0.0 
peacocks-in-space-rainglow-syntax 1.0.0 
peel-contrast-rainglow-syntax 1.0.0 
peel-light-rainglow-syntax 1.0.0 
peel-rainglow-syntax 1.0.0 
penitent-contrast-rainglow-syntax 1.0.0 
penitent-light-rainglow-syntax 1.0.0 
penitent-rainglow-syntax 1.0.0 
php-fmt 0.1.2 
piggy-contrast-rainglow-syntax 1.0.0 
piggy-light-rainglow-syntax 1.0.0 
piggy-rainglow-syntax 1.0.0 
pleasure-contrast-rainglow-syntax 1.0.0 
pleasure-light-rainglow-syntax 1.0.0 
pleasure-rainglow-syntax 1.0.0 
potpourri-contrast-rainglow-syntax 1.0.0 
potpourri-light-rainglow-syntax 1.0.0 
potpourri-rainglow-syntax 1.0.0 
prime-contrast-rainglow-syntax 1.0.0 
prime-light-rainglow-syntax 1.0.0 
prime-rainglow-syntax 1.0.0 
rainbow-contrast-rainglow-syntax 1.0.0 
rainbow-light-rainglow-syntax 1.0.0 
rainbow-rainglow-syntax 1.0.0 
rebellion-contrast-rainglow-syntax 1.0.0 
rebellion-light-rainglow-syntax 1.0.0 
rebellion-rainglow-syntax 1.0.0 
revelation-contrast-rainglow-syntax 1.0.0 
revelation-light-rainglow-syntax 1.0.0 
revelation-rainglow-syntax 1.0.0 
scorch-contrast-rainglow-syntax 1.0.0 
scorch-light-rainglow-syntax 1.0.0 
scorch-rainglow-syntax 1.0.0 
service-contrast-rainglow-syntax 1.0.0 
service-light-rainglow-syntax 1.0.0 
service-rainglow-syntax 1.0.0 
shrek-contrast-rainglow-syntax 1.0.0 
shrek-light-rainglow-syntax 1.0.0 
shrek-rainglow-syntax 1.0.0 
slate-contrast-rainglow-syntax 1.0.0 
slate-light-rainglow-syntax 1.0.0 
slate-rainglow-syntax 1.0.0 
slime-contrast-rainglow-syntax 1.0.0 
slime-light-rainglow-syntax 1.0.0 
slime-rainglow-syntax 1.0.0 
snappy-contrast-rainglow-syntax 1.0.0 
snappy-light-rainglow-syntax 1.0.0 
snappy-rainglow-syntax 1.0.0 
solarflare-contrast-rainglow-syntax 1.0.0 
solarflare-light-rainglow-syntax 1.0.0 
solarflare-rainglow-syntax 1.0.0 
soup-contrast-rainglow-syntax 1.0.0 
soup-light-rainglow-syntax 1.0.0 
soup-rainglow-syntax 1.0.0 
sourlick-contrast-rainglow-syntax 1.0.0 
sourlick-light-rainglow-syntax 1.0.0 
sourlick-rainglow-syntax 1.0.0 
spearmint-contrast-rainglow-syntax 1.0.0 
spearmint-light-rainglow-syntax 1.0.0 
spearmint-rainglow-syntax 1.0.0 
spitfire-contrast-rainglow-syntax 1.0.0 
spitfire-light-rainglow-syntax 1.0.0 
spitfire-rainglow-syntax 1.0.0 
stark-contrast-rainglow-syntax 1.0.0 
stark-light-rainglow-syntax 1.0.0 
stark-rainglow-syntax 1.0.0 
stasis-contrast-rainglow-syntax 1.0.0 
stasis-light-rainglow-syntax 1.0.0 
stasis-rainglow-syntax 1.0.0 
stealth-contrast-rainglow-syntax 1.0.0 
stealth-light-rainglow-syntax 1.0.0 
stealth-rainglow-syntax 1.0.0 
storm-contrast-rainglow-syntax 1.0.0 
storm-light-rainglow-syntax 1.0.0 
storm-rainglow-syntax 1.0.0 
super-contrast-rainglow-syntax 1.0.0 
super-light-rainglow-syntax 1.0.0 
super-rainglow-syntax 1.0.0 
tame-contrast-rainglow-syntax 1.0.0 
tame-light-rainglow-syntax 1.0.0 
tame-rainglow-syntax 1.0.0 
tetra-contrast-rainglow-syntax 1.0.0 
tetra-light-rainglow-syntax 1.0.0 
tetra-rainglow-syntax 1.0.0 
tickle-contrast-rainglow-syntax 1.0.0 
tickle-light-rainglow-syntax 1.0.0 
tickle-rainglow-syntax 1.0.0 
tonic-contrast-rainglow-syntax 1.0.0 
tonic-light-rainglow-syntax 1.0.0 
tonic-rainglow-syntax 1.0.0 
tribal-contrast-rainglow-syntax 1.0.0 
tribal-light-rainglow-syntax 1.0.0 
tribal-rainglow-syntax 1.0.0 
tron-contrast-rainglow-syntax 1.0.0 
tron-light-rainglow-syntax 1.0.0 
tron-rainglow-syntax 1.0.0 
turnip-contrast-rainglow-syntax 1.0.0 
turnip-light-rainglow-syntax 1.0.0 
turnip-rainglow-syntax 1.0.0 
tweed-contrast-rainglow-syntax 1.0.0 
tweed-light-rainglow-syntax 1.0.0 
tweed-rainglow-syntax 1.0.0 
userscape-contrast-rainglow-syntax 1.0.0 
userscape-light-rainglow-syntax 1.0.0 
userscape-rainglow-syntax 1.0.0 
vegetable-contrast-rainglow-syntax 1.0.0 
vegetable-light-rainglow-syntax 1.0.0 
vegetable-rainglow-syntax 1.0.0 
violaceous-contrast-rainglow-syntax 1.0.0 
violaceous-light-rainglow-syntax 1.0.0 
violaceous-rainglow-syntax 1.0.0 
vision-colorblind-rainglow-syntax 1.0.0 
vision-light-colorblind-rainglow-syntax 1.0.0 
volatile-contrast-rainglow-syntax 1.0.0 
volatile-light-rainglow-syntax 1.0.0 
volatile-rainglow-syntax 1.0.0 
vue-autocomplete 0.1.1 
warlock-contrast-rainglow-syntax 1.0.0 
warlock-light-rainglow-syntax 1.0.0 
warlock-rainglow-syntax 1.0.0 
waste-contrast-rainglow-syntax 1.0.0 
waste-light-rainglow-syntax 1.0.0 
waste-rainglow-syntax 1.0.0 
yitzchok-contrast-rainglow-syntax 1.0.0 
yitzchok-light-rainglow-syntax 1.0.0 
yitzchok-rainglow-syntax 1.0.0 
yule-contrast-rainglow-syntax 1.0.0 
yule-light-rainglow-syntax 1.0.0 
yule-rainglow-syntax 1.0.0 
zacks-contrast-rainglow-syntax 1.0.0 
zacks-light-rainglow-syntax 1.0.0 
zacks-rainglow-syntax 1.0.0 
```

**Comment by Ingramz** [comment]
@ThibaultModat Thank you for the report, however I'm having difficulties replicating this. Are you using the *.deb package from atom.io ?

**Comment by ThibaultModat** [comment]
@Ingramz Thanks for the quick reply

I think i used the deb package, now it updates itself with the repo `deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
`

    $ atom --version
    Atom    : 1.31.0
    Electron: 2.0.7
    Chrome  : 61.0.3163.100
    Node    : 8.9.3

**Comment by ThibaultModat** [comment]
The atom 1.31.1 update didn't change anything

**Comment by Ingramz** [comment]
Do you get the error message every time you launch Atom?

**Comment by ThibaultModat** [comment]
Yes

**Comment by Ingramz** [comment]
Check if Packages -> language-blade -> settings contains the setting "Use Blade Comments":

![screen shot 2018-09-28 at 10 47 54](https://user-images.githubusercontent.com/1017132/46195102-ffe42b00-c30b-11e8-914d-faba78d24723.png)

**Comment by ThibaultModat** [comment]
Nope
![screenshot from 2018-09-28 09-51-58](https://user-images.githubusercontent.com/5517123/46195284-3453e900-c304-11e8-88f5-f0e8a424a809.png)

**Comment by Ingramz** [comment]
I published a package update with a potential fix, please try.

**Comment by ThibaultModat** [comment]
It works! Thank you
